[DOC, WIP] Added a case study based on multitouch attribution notebook
py-why/py-why.github.io pull request #10
Opened 2023-01-13 20:09 UTC by robertness

This is a case study based on a jupyter notebook using DoWhy, EconML and DECI (a discovery algorithm) to study multitouch attribution.

I converted the notebook to a markdown file for Github.io, and put the notebook itself in an "artifacts" folder.

2023-01-25 15:12 UTC, emrekiciman commented
Thanks for preparing this, @robertness .  It's important to add more of these complete case studies and I'm inclined to approve.  I also like how this one example goes through the end-to-end process, and I can imagine linking from here / to here from in-depth studies of each analysis stage, i.e., like a notebook that goes through all of the relevant estimation algorithms in the context of this case study and explaining their relative advantages, etc.  

I had a couple questions:

1) Can we add this notebook to the DoWhy repository as an advanced test as well?  If we are publishing a notebook like this, we should validate that new PRs don't accidentally break the notebook for users.
2) In the github-rendered notebook, 90% of the notebook seems to be debug output from the causal discovery run.  Is that removed from the markdown version?
3) When I view the markdown version of the notebook (i.e., by clicking 'view file' in the PR), I don't think I'm seeing the fully-rendered version of the markdown.  Is there a way to see how github pages will render this markdown?
4) when running the checks on the PR, the deploy step is failing.  @dworthen, do you know what this error message means?
5) in the notebook, in advanced, there's a version of the DAG that is rendered with a bad layout (around cell 51 or 55, I think.  Can we replace that with a better layout, like the DAG that is rendered immediately after the causal discovery step?
6) do we want to run causal discovery twice (once without constraints and once with constraints) or should we just run it only with the constraints?
7) is the do-discover API ready to handle the causal discovery functionality here, or is that a goal for later?

2023-01-25 15:17 UTC, dworthen requested changes

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +summary: A tutorial on using various PyWhy tools to execute a causal modeling workflow.
I think we should provide an image and alt description to show up on the home page. Something like

image: case_studies/figures/06_multi_investment_sales_attribution/investment_policy_scatterplot.png
image-alt: Investment policy scatterplot

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +link: https://github.com/py-why/py-why.github.io/blob/main/_case_studies/artifacts/06_multi_investment_sales_attribution/Multi-investment Sales Attribution.ipynb
The link attribute will cause the rendered card to link out to the url provided instead of linking to the rendered markdown for this page. The link attribute is for cards in which their contents live in external locations. To render this page, remove the link attribute in the YAML front matter and then provide a markdown link somewhere in the page linking to the resource:

[Multi-investment Sales Attribution notebook](https://github.com/py-why/py-why.github.io/blob/main/_case_studies/artifacts/06_multi_investment_sales_attribution/Multi-investment Sales Attribution.ipynb)

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +::: {.cell .markdown}
::: lines should be deleted.

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +`<img src="https://www.microsoft.com/en-us/research/uploads/prod/2020/05/Attribution.png" width="400">`{=html}
I don't believe Jekyll markdown supports html. This will need to be converted  to the markdown equivalent in the form `![Image Alt Text](URL)`

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +``` {.python}
Should be ` ```python` without the `{.}`

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +  -----------------------------------------------------------------------
Markdown tables need to be in the following format

```markdown
Column A | Column B | Column C
---------|----------|---------
 A1 | B1 | C1
 A2 | B2 | C2
 A3 | B3 | C3
```

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +<div>
Need to convert html to markdown.

2023-01-25 15:17 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +link: https://github.com/py-why/py-why.github.io/blob/main/_case_studies/artifacts/06_multi_investment_sales_attribution/Multi-investment Sales Attribution.ipynb
After reading some of this file I realized it is the notebook contents. Do you wish to render the notebook directly in the website or link to it on github? If you wish to link to it on github then you can delete all the markdown content in this file and leave in the link attribute in the YAML front matter.

2023-01-25 15:22 UTC, dworthen commented
@emrekiciman and @robertness, there is a check in the deploy step for it to run only when it is a push/merge with the main branch. For a PR from a local branch the deploy step runs but skips doing anything and tends to indicate this. The problem here is that the step doesn't even want to start when the PR comes from a remote branch from a different repo so it is failing before it can skip anything. I will look into updating the step to skip instead of fail in this case.

2023-01-25 15:43 UTC, dworthen commented on _case_studies/06_multi_investment_sales_attribution.md
> +::: {.cell .markdown}
@emrekiciman, this PR should fix the deploy step error: https://github.com/py-why/py-why.github.io/pull/11

2023-01-25 15:44 UTC, dworthen commented
@emrekiciman, this PR fixes the deploy step error: https://github.com/py-why/py-why.github.io/pull/11

2023-01-26 01:52 UTC, robertness commented
@emrekiciman 

> Can we add this notebook to the DoWhy repository as an advanced test as well? If we are publishing a notebook like this, we should validate that new PRs don't accidentally break the notebook for users.

A better solution would be this: https://github.com/marketplace/actions/run-notebook
https://github.com/py-why/dowhy/issues/830

> In the github-rendered notebook, 90% of the notebook seems to be debug output from the causal discovery run. Is that removed from the markdown version?

I'm going to remove the markdown code and just point to the notebook, since Github renders notebooks.

> When I view the markdown version of the notebook (i.e., by clicking 'view file' in the PR), I don't think I'm seeing the fully-rendered version of the markdown. Is there a way to see how github pages will render this markdown?

No.  At this point I'm just going to point to the rendered notebook.

> when running the checks on the PR, the deploy step is failing. @dworthen, do you know what this error message means?

It is because I am committing from a fork.  I'll resubmit from the original repo.

>  in the notebook, in advanced, there's a version of the DAG that is rendered with a bad layout (around cell 51 or 55, I think. Can we replace that with a better layout, like the DAG that is rendered immediately after the causal discovery step?

I'll take a look.

>  do we want to run causal discovery twice (once without constraints and once with constraints) or should we just run it only with the constraints?

I'll edit to do it with only constraints.

> is the do-discover API ready to handle the causal discovery functionality here, or is that a goal for later?

Yes.  I'll reimplement to incorporate dodiscover in a subsequent PR.

2023-01-29 23:23 UTC, closed without merging

2023-01-29 23:24 UTC, robertness commented
Closing, going to reopen in the original repo instead of this fork (to avoid deploy issues).

2023-01-30 15:14 UTC, dworthen commented
> Closing, going to reopen in the original repo instead of this fork (to avoid deploy issues).

@robertness, I merged a PR that fixes the deploy error during PR requests. Users submitting PR for review from external repos should no longer get the deploy error and instead the deploy step will be skipped as it should only occur during merges/pushes to main from those who have access to update main.